# FDailyRewards – konfigurace denních odměn

debug: true

# Time after which it will be next day for rewards
day_reset_time: "04:15"

# Time interval in minutes to remind players about available reward claim
reward_claim_available_interval: 30

message_prefix: "<blue>[ FDailyRewards ]</blue>"

reward_claim_available_message: "Daily reward is available for claim! use /fdailyrewards to claim it"
reward_claim_available_loreline: "<red>Click to claim your reward"
reward_claim_available_tommorow_loreline: "<red>\nWill be available tomorrow"
reward_claim_available_2_days_loreline: "<red>\nWill be available in 2 days"
reward_vip_locked_loreline: "<red>This reward is locked for VIP players only."
reward_vip_can_skip: "<red>As a VIP player, you can skip days to claim this reward."
reward_already_claimed: "<red>You have already claimed this reward"
reward_vip_only: "<red>This reward is available for VIP players only."
reward_not_yet_available: "<red>This reward is not yet available."
reward_previous_not_claimed: "<red>You must claim the previous day's reward first."
reward_cannot_yet: "<red>You cannot claim this reward yet."
reward_already_claimed_today: "<red>You have already claimed a reward today."

login_rewarded: "<green>You have received your premium daily login reward!"
login_commands:
  - "give %player_name%  diamond 1"
  - "give %player_name%  gold_ingot 5"

reward_claimed_item:
    material: GREEN_WOOL
    customModelData: 0
    name: "<red>Odměna vyzvednuta"
    lore:
        - ""
        - "<red>Už jsi si vyzvedl svou odměnu za tento den."

reward_claimed_item_vip:
    material: BLUE_WOOL
    customModelData: 0
    name: "<red>Odměna vyzvednuta (VIP)"
    lore:
        - ""
        - "<red>Už jsi si vyzvedl svou VIP odměnu za tento den."