# FDailyRewards – konfigurace denních odměn

debug: true

# Time after which it will be next day for rewards
day_reset_time: "04:15"

message_prefix: "<blue>[ FDailyRewards ]</blue>"

# Deprecated - do not use
menu_title: "<red>Denní odměny"
info_title: "<red>Information"
info_lore:
  - ""
  - "<red>Získej denní odměny!"
  - "<red>Přihlaš se každý den pro speciální odměny."

reward_claim_available_loreline: "<red>Click to claim your reward"
reward_claim_available_tommorow_loreline: "<red>\nWill be available tomorrow"
reward_vip_locked_loreline: "<red>This reward is locked for VIP players only."
reward_vip_can_skip: "<red>As a VIP player, you can skip days to claim this reward."
reward_already_claimed: "<red>You have already claimed this reward"
reward_vip_only: "<red>This reward is available for VIP players only."
reward_not_yet_available: "<red>This reward is not yet available."
reward_previous_not_claimed: "<red>You must claim the previous day's reward first."
reward_cannot_yet: "<red>You cannot claim this reward yet."
reward_already_claimed_today: "<red>You have already claimed a reward today."

reward_claimed_item:
    material: GREEN_WOOL
    customModelData: 0
    name: "<red>Odměna vyzvednuta"
    lore:
        - ""
        - "<red>Už jsi si vyzvedl svou odměnu za tento den."


rewards:
  "1":
    vip: false
    item:
      material: PAPER
      customModelData: 0
      name: "Den 1 odměna"
      lore:
        - ""
        - "<red>Získej malý start!"
    commands:
      - "give %player_name% minecraft:bread 3"
      - "tell %player_name% Užij si odměnu za den 1!"

  "2":
    vip: true
    item:
      material: DIAMOND
      customModelData: 0
      name: "VIP – Den 2"
      lore: "Prémiová odměna pro VIP hráče"
    commands:
      - "give %player_name% minecraft:diamond 1"
      - "tell %player_name% VIP odměna za den 2!"

  "3":
    vip: false
    item:
      material: IRON_INGOT
      customModelData: 0
      name: "Den 3 odměna"
      lore:
        - ""
        - "Pokračuj ve sbírání!"
    commands:
      - "give %player_name% minecraft:iron_ingot 5"
      - "tell %player_name% Odměna za den 3!"

  "4":
    vip: false
    item:
      material: GOLD_INGOT
      customModelData: 0
      name: "Den 4 odměna"
      lore:
        - ""
        - "Zlatá příležitost!"
    commands:
      - "give %player_name% minecraft:gold_ingot 3"
      - "tell %player_name% Odměna za den 4!"

  "5":
    vip: true
    item:
      material: EMERALD
      customModelData: 0
      name: "VIP – Den 5"
      lore: "Prémiová odměna pro VIP hráče"
    commands:
      - "give %player_name% minecraft:emerald 2"
      - "tell %player_name% VIP odměna za den 5!"
  "6":
    vip: false
    item:
      material: COOKED_BEEF
      customModelData: 0
      name: "Den 6 odměna"
      lore:
        - ""
        - "Dobrá strava pro dobrodruha!"
    commands:
      - "give %player_name% minecraft:cooked_beef 4"
      - "tell %player_name% Odměna za den 6!"