# FDailyRewards – konfigurace denních odměn

debug: true

# Time after which it will be next day for rewards
day_reset_time: "04:15"

menu_title: "Denní odměny"

menu:
  title: "Denní odměny"
  infoTitle: "Informace"
  infoLore: "Klikni pro víc informací."

#
# Dvě podporované struktury:
# 1) Mapa: rewards.<den>.*  (doporučeno)
# 2) List: rewardsList: - day: ...
#
# Klíče:
# - vip: true/false (zda je odměna jen pro VIP)
# - item:
#     material: název materiálu (např. PAPER, DIAMOND)
#     customModelData: číslo CMD (volitelné)
#     name: zobrazený název (volitelné)
#     lore: může být list stringů nebo jeden string (volitelné)
# - commands: list příkazů spuštěných při vyzvednutí (bez lomítka). Lze použít placeholdery dle vašeho systému.

rewards:
  "1":
    vip: false
    item:
      material: PAPER
      customModelData: 0
      name: "Den 1 odměna"
      lore:
        - ""
        - "Získej malý start!"
    commands:
      - "give %player_name% minecraft:bread 3"
      - "tell %player_name% Užij si odměnu za den 1!"

  "2":
    vip: true
    item:
      material: DIAMOND
      customModelData: 0
      name: "VIP – Den 2"
      lore: "Prémiová odměna pro VIP hráče"
    commands:
      - "give %player_name% minecraft:diamond 1"
      - "tell %player_name% VIP odměna za den 2!"

# Alternativní zápis přes list (pokud preferujete):
# rewardsList:
#   - day: 3
#     vip: false
#     item:
#       material: IRON_INGOT
#       name: "Den 3 odměna"
#       lore:
#         - ""
#         - "Další zásoby"
#     commands:
#       - "give %player_name% minecraft:iron_ingot 5"
